### ISSUE TITLE
Default duration should be only an example

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#115]
## Issue

Within API documentation the default session duration of 24 hours is only given as an example:

* "_... or the default session expiration time has been reached (within an example provider implementation it is set to 24hrs)_"
* "_When not specified, a default session duration (e.g. 24 hours) is applied_"

but in the API YAML file it is fixed:

```
duration:
          type: integer
          example: 86400
          description: |
            Session duration in seconds. Maximal value of 24 hours is used if not set.
            After session has expired the client will receive QOS_STATUS_CHANGED event with 
             - qosStatus is 'UNAVAILABLE', and, 
             - statusInfo is 'DURATION_EXPIRED'. 
            See notification callback.
          format: int32
          minimum: 1
          maximum: 86400
          default: 86400
```

## Proposal:

Omit "Maximal value of 24 hours is used if not set" and the `default: 86400` line from the general YAML, 24 hours is then still the maximum and implicit default value, if there is not other default value defined by the network operator. A network operator can set a specific default for their network enviroment. A PR should also make the documentation more precise and encourage developers to set the duration if they expect a certain duration.

## Background:

We would like to set a short default duration in certain networks (using environment variable), e.g. in case of test environments (as a mitigation to issue described in #101).
Also a default of 24 hrs might be too long from business perspective in production networks.
