### ISSUE TITLE
Format 'ipv4' is more restrictive than the pattern in Data Type 'Ipv4Address'

### ISSUE THREAD

**Issue by tlohmar** [camaraproject/QualityOnDemand#146]
**Problem description**
The Data Type 'Ipv4Address' is defined as 

```
Ipv4Address:
      type: string
      format: ipv4
      pattern: '^([01]?\d\d?|2[0-4]\d|25[0-5])(?:\.(?:[01]?\d\d?|2[0-4]\d|25[0-5])){3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
      example: "192.168.0.1/24"
```
The format 'ipv4' is defined by the [OpenAPI specification](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-7.3.4) as "An IPv4 address according to the "dotted-quad" ABNF syntax as
defined in [RFC 2673, section 3.2](https://datatracker.ietf.org/doc/html/rfc2673#section-3.2) [[RFC2673](https://datatracker.ietf.org/doc/html/rfc2673)].". The "dotted-quad" does not allow the addition of a netmask, e.g. "/24"

The regular expression of the pattern allows also the addition of a netmask. The provided example "192.168.0.1/24" is not comply with the format 'ipv4'

A similar issue exist for data type Ipv6Address.

**Expected behavior**
The suggested correction is to replace 'ipv4' with 'string' and rely on the regular expression in pattern.
