### ISSUE TITLE
Add three_legged to securitySchemes

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#161]
**Problem description**

* Currently QoD is only considering clientCredentials as security mechanism (along with apiKey for notifications). 
* 3-legged access tokens have to be supported as well to deal with privacy and consent management.
  

**Possible evolution**

There are currently 2 models for three_legged used across the rest of WGs. It would be good to have a clear guideline to choose one:

```
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/authorize
          tokenUrl: https://auth.example.com/token
          scopes:
            xxx: yyyy    
```

```
     type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

**Additional context**

The requirement to have 3-legged access tokens is validated with our Legal and Privacy teams so it is something mandatory to deploy the API in certain scenarios.

If there is consensus for it we could add it for next Release v0.9 .
