### ISSUE TITLE
Update the "server"-section to align with other CAMARA specifications

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#251]
**Current description**
```yaml
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: qod/v0
        description: Base path for the QoD API
```
**Expected behavior**

```yaml
servers:
  - url: "{apiRoot}/qod/v0"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
```

**Additional context**
Related to https://github.com/camaraproject/NumberVerification/issues/77
