### ISSUE TITLE
Error behaviour when session cannot be created due to "time cap" limitation

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#257]
**Problem description**

Use case would be that QoD is productized as number of N QoD minutes or sessions per period and after reaching that limit a new QoD session, or a session duration extension, is requested. What would be the right error to be answered? As an enhancement this can be added as example to document the expected behaviour.

**Possible evolution**
Add an explicit example to /paths/sessions/POST/responses/"429"/content/"application/json"/examples:

In the guidelines there is a Service Exception documented as: 

| Error Code | Description |
|---|---|
| `TOO_MANY_REQUESTS` | Either out of resource quota or reaching rate limiting. |

```
SessionsTimeCapExceeded:
  summary: The requested duration exceeds the overall sessions time cap for this device in certain period of time or contract duration.
  value:
    status: 429
    code: TOO_MANY_REQUESTS
    message: The requested session exceeds the allocated quota for this device: Sessions time cap limit exceeded
```

**Alternative solution**
An alternative code may be created especifically for `QUOTA_REACHED`.

**Additional context**

Initially opened as discussion: https://github.com/camaraproject/QualityOnDemand/discussions/231
