### ISSUE TITLE
Return 422 instead of 501 if the service is not implemented for specified device 

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#315]
**Problem description**

We are currently defining 501 as a valid response for the creation of a session. We have/had defined the message as "Service not implemented for the specified user device". 

But Commonalities defines the error response (correctly) as "This functionality is not implemented yet." (which means the complete method). For our intended error response there is 

```
GENERIC_422_DEVICE_NOT_APPLICABLE:
              description: Service is not available for the provided device
              value:
                status: 422
                code: DEVICE_NOT_APPLICABLE
                message: The service is not available for the provided device.
```

In addition there is a discussion that 501 within the API Spec might be used in future to indicate that the implementation of a method is "optional". We don't want to indicate that for createSession

**Expected behavior**

Delete 501 from the valid error responses, add 422 with the above definition to the createSession.

**Alternative solution**

**Additional context**
