### ISSUE TITLE
Behaviour when extending not AVAILABLE session

### ISSUE THREAD

**Issue by jlurien** [camaraproject/QualityOnDemand#351]
**Problem description**
Current spec do not indicate the expected behaviour when the extension of the duration of a session in status other than AVAILABLE is requested

**Expected action**
Agree on the expected result, and update spec and tests. 

For sessions with qosStatus = REQUESTED, implementation may accept the request and take into account the petition when the session is activated, or return a success without modifying the original duration (ignoring the request), or even return an error indicating that this request is not acceptable  in  the current state. 
For sessions with qosStatus = UNAVAILABLE, implementation may return a success without modifying the duration (ignoring the request), or return an error indicating that this request is not acceptable  in the current state.

**Comment by maxl2287** [comment]
Hi @jlurien,

Thanks for bringing this to our attention.

Regarding the expected behavior when extending the duration of a session in a status other than `AVAILABLE`, I propose the following approach:

**For sessions with qosStatus = REQUESTED**
This is because the session is still pending activation, and extending its duration at this point might lead to unexpected behavior or conflicts.

**For sessions with qosStatus = UNAVAILABLE**
This is because the session is no longer active, and extending its duration would not have any effect.

```json
{
  "status": 409,
  "code": "SESSION_EXTENSION_NOT_ALLOWED",
  "message": "Extending the session duration is not allowed in the current state ({qosStatus}). The session must be in the AVAILABLE state."
}
```

By returning an error in both cases, we maintain consistency and avoid potential ambiguities.

Wdyt?

cc @hdamker

**Comment by hdamker** [comment]
@jlurien @maxl2287 Seems that there are not more opinions yet. Do we want to follow the path to return errors if the session is not in state AVAILABLE?

In this case I would propose a small addition in the description of the operation:

Current:
`Extend the overall session duration of an active QoS session.`
Proposal:
`Extend the overall session duration of an active QoS session (with qosStatus = AVAILABLE)`

Regarding the error code we can then go with 400 ("Bad Request"), adding the following example within GenericExtendSessionDuration400:

```
            SessionExtensionNotAllowed:
              description: Session must be in AVAILABLE state to get extended
              value:
                status: 400
                code: QUALITY_ON_DEMAND.SESSION_EXTENSION_NOT_ALLOWED
                message: Extending the session duration is not allowed in the current state ({qosStatus}). The session must be in the AVAILABLE state.
```

WDYT? Doing it still for 0.11.0? Adding only the description clarification or also the error example?
