### ISSUE TITLE
Update reference to the CAMARA API Design Guidelines

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/QualityOnDemand#438]
**Problem description**
The reference to the CAMARA API design guidelines is outdated and needs to be corrected.

**Expected behavior**

```yaml
  - name: 📖 CAMARA API Design Guidelines
    url: https://github.com/camaraproject/Commonalities/blob/main/documentation/CAMARA-API-Design-Guide.md
    about: Please refer to the design guidelines.
```
