### ISSUE TITLE
Inconsistencies in the spec

### ISSUE THREAD

**Issue by SfnUser** [camaraproject/QualityOnDemand#80]
In `CreateSession`, `400` error response the following example is provided.
```
                UePortsRequired:
                  summary: uePorts is required
                  value: 
                    code: INVALID_INPUT
                    message: "Expected property is missing: uePorts"
```
This meant to say that `uePorts` is a required param. However, the `CreateSession` definition mentiones `uePorts` as optional param.
Which one is correct?

Same way in the below example, it is mentioned port ranges are not allowed for `uePorts`. However, `uePorts` is of type `PortSpec` and there is no restriction on specifying ranges.
```
                UePortsRangesNotAllowed:
                  summary: Ranges at uePorts are not allowed
                  value: 
                    code: INVALID_INPUT
                    message: "Ranges not allowed: uePorts"
```
If these examples are not upto date, could we please remove them?
